(function(){var e="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function h(){h=function(){};g.Symbol||(g.Symbol=k)}var l=0;function k(a){return"jscomp_symbol_"+(a||"")+l++}
function n(){h();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&e(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return p(this)}});n=function(){}}function p(a){var b=0;return q(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function q(a){n();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}function r(a){n();h();n();var b=a[Symbol.iterator];return b?b.call(a):p(a)}
function u(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var v=/:(80|443)$/,w=document.createElement("a"),x={};
function y(a){a=a&&"."!=a?a:location.href;if(x[a])return x[a];w.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return y(w.href);var b="80"==w.port||"443"==w.port?"":w.port,b="0"==b?"":b,c=w.host.replace(v,"");return x[a]={hash:w.hash,host:c,hostname:w.hostname,href:w.href,origin:w.origin?w.origin:w.protocol+"//"+c,pathname:"/"==w.pathname.charAt(0)?w.pathname:"/"+w.pathname,port:b,protocol:w.protocol,search:w.search}}var z=[];
function A(a,b){var c=this;this.context=a;this.h=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.a=[];this.b=[];this.g=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return c.b[c.b.length-1].apply(null,[].concat(b instanceof Array?b:u(r(b))))};this.c?a.set(b,this.g):a[b]=this.g}function B(a,b){b=a.a.indexOf(b);-1<b&&(a.a.splice(b,1),0<a.a.length?C(a):(b=z.indexOf(a),-1<b&&(z.splice(b,1),a.c?a.context.set(a.h,a.f):a.context[a.h]=a.f)))}
function C(a){a.b=[];for(var b,c=0;b=a.a[c];c++){var d=a.b[c-1]||a.f.bind(a.context);a.b.push(b(d))}}function D(a,b){var c=z.filter(function(c){return c.context==a&&c.h==b})[0];c||(c=new A(a,b),z.push(c));return c}var E=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(var d=0,f=c.length;d<f;d++){var t=Object(c[d]),m;for(m in t)Object.prototype.hasOwnProperty.call(t,m)&&(a[m]=t[m])}return a},F={i:1,j:2,l:3,o:4,s:5,u:6,v:7,w:8,A:9,m:10},G=Object.keys(F).length;
function H(a,b){var c=F.i;a.set("\x26_av","2.4.1");var d=a.get("\x26_au"),d=parseInt(d||"0",16).toString(2);if(d.length<G)for(var f=G-d.length;f;)d="0"+d,f--;c=G-c;d=d.substr(0,c)+1+d.substr(c+1);a.set("\x26_au",parseInt(d||"0",2).toString(16));this.a=E({},b);this.g=a;this.b=this.a.stripQuery&&this.a.queryDimensionIndex?"dimension"+this.a.queryDimensionIndex:null;this.f=this.f.bind(this);this.c=this.c.bind(this);b=this.f;c=D(a,"get");c.a.push(b);C(c);b=this.c;a=D(a,"buildHitTask");a.a.push(b);C(a)}
H.prototype.f=function(a){var b=this;return function(c){if("page"==c||c==b.b){var d={location:a("location"),page:a("page")};return I(b,d)[c]}return a(c)}};H.prototype.c=function(a){var b=this;return function(c){var d=I(b,{location:c.get("location"),page:c.get("page")});c.set(d,null,!0);a(c)}};
function I(a,b){var c=y(b.page||b.location),d=c.pathname;if(a.a.indexFilename){var f=d.split("/");a.a.indexFilename==f[f.length-1]&&(f[f.length-1]="",d=f.join("/"))}"remove"==a.a.trailingSlash?d=d.replace(/\/+$/,""):"add"==a.a.trailingSlash&&(/\.\w+$/.test(d)||"/"==d.substr(-1)||(d+="/"));d={page:d+(a.a.stripQuery?J(a,c.search):c.search)};b.location&&(d.location=b.location);a.b&&(d[a.b]=c.search.slice(1)||"(not set)");return"function"==typeof a.a.urlFieldsFilter?(b=a.a.urlFieldsFilter(d,y),c={page:b.page,
location:b.location},a.b&&(c[a.b]=b[a.b]),c):d}function J(a,b){if(Array.isArray(a.a.queryParamsWhitelist)){var c=[];b.slice(1).split("\x26").forEach(function(b){var d=r(b.split("\x3d"));b=d.next().value;d=d.next().value;-1<a.a.queryParamsWhitelist.indexOf(b)&&d&&c.push([b,d])});return c.length?"?"+c.map(function(a){return a.join("\x3d")}).join("\x26"):""}return""}H.prototype.remove=function(){var a=this.f;B(D(this.g,"get"),a);a=this.c;B(D(this.g,"buildHitTask"),a)};
(function(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b})("cleanUrlTracker",H);})();
//# sourceMappingURL=autotrack.custom.js.map